name: CI

on: 
  pull_request:
    branches:
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: running unit tests
      run: |
        npm install
        npm run test:update
